### ISSUE TITLE
Error Launching Local Server: throw new MongooseError('The `uri` parameter to `openUri()` must be a ' +

### ISSUE THREAD

**Issue by look-its-ashton** [ksdt/API#3]
I'm trying to launch the server with `node server.js` but each time I get the following error

C:\Users\gtdub\Documents\Classes\SP2022\KSDT\API\node_modules\mongoose\lib\connection.js:689
    throw new MongooseError('The `uri` parameter to `openUri()` must be a ' +
          ^

My repo is up to date and I defined an .env file in the root but this problem persists.

**Comment by waynarbocangel** [comment]
This relates to the correct setup of the .env file.
